spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: ERROR