spring:
  application:
    name: authentication-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: ${SERVER_PORT:8083}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
jwt:
  secret: KXiUPknkoVDCHdNrrYnxmA5oQLbv+LE7eHG8vkk71fjEPq0lmlZKwBhUVLUqKSmGam8P4kWxXKTGCDRgpZ5BMA==

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR
  pattern:
    level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  tracing:
    sampling:
      probability: 1.0
    propagation:
      type: B3
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/api/v2/spans
